# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c78e450cf7fea7888e3ea14f563c73726aa4bcb6354aaf6eb03100d16fb513d44ae70e09c147843c72d355f54cc87a9bd58d77708d966cf483e8d843a25d248

test:
  secret_key_base: c76d8c3465c1fb7ebeab2db70f32ca0f7eb35fc7b37743c6e1f444e91338a5aca25d9f7c73e06714c24fd0a642d6c6992a4368306eba1037ff24bd97f55297bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
